"""
mutual_fund_analysis.py
------------------------
Full pipeline:
  1. Load raw mutual fund dataset (CSV generated by generate_dataset.py)
  2. Data Cleaning
  3. Descriptive Statistics
  4. Normalization (MinMaxScaler)
  5. Custom Scoring & Ranking
  6. Extract Top 30 Funds
  7. Export to Excel
  8. Generate Charts (saved as PNG files in charts/)

Usage:
    python mutual_fund_analysis.py

Requires:
    data/mutual_funds_raw.csv  (run generate_dataset.py first)
"""

import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

# ─── Paths ────────────────────────────────────────────────────────────────────
DATA_DIR = "data"
CHARTS_DIR = "charts"
RAW_CSV = os.path.join(DATA_DIR, "mutual_funds_raw.csv")
TOP30_XLSX = os.path.join(DATA_DIR, "top_30_mutual_funds.xlsx")

os.makedirs(CHARTS_DIR, exist_ok=True)

# ─── Palette ──────────────────────────────────────────────────────────────────
sns.set_theme(style="darkgrid", palette="muted")
COLORS = sns.color_palette("muted", 10)

# ==============================================================================
# 1. LOAD DATA
# ==============================================================================

def load_data(path=RAW_CSV):
    print("=" * 60)
    print("STEP 1 — Loading dataset")
    print("=" * 60)

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Dataset not found at '{path}'.\n"
            "Run  python generate_dataset.py  first to fetch data from mfapi.in"
        )

    df = pd.read_csv(path)
    print(f"  Loaded {len(df)} rows, {df.shape[1]} columns")
    print(f"  Columns: {list(df.columns)}\n")
    return df


# ==============================================================================
# 2. DATA CLEANING
# ==============================================================================

def clean_data(df):
    print("=" * 60)
    print("STEP 2 — Data Cleaning")
    print("=" * 60)

    initial = len(df)

    # Drop rows with no scheme name
    df = df[df["scheme_name"].notna() & (df["scheme_name"] != "")]

    # Convert numeric columns
    numeric_cols = ["latest_nav", "return_1y", "return_3y", "fund_age_years"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Drop rows where key metrics are missing
    df = df.dropna(subset=["return_1y", "return_3y", "latest_nav"])

    # Remove funds with negative NAV (data error)
    df = df[df["latest_nav"] > 0]

    # Remove extreme outliers in returns (>500% or <-100%)
    df = df[(df["return_1y"] >= -100) & (df["return_1y"] <= 500)]
    df = df[(df["return_3y"] >= -100) & (df["return_3y"] <= 500)]

    # Standardize category text
    for col in ["scheme_type", "scheme_category", "scheme_sub_category", "fund_house"]:
        if col in df.columns:
            df[col] = df[col].fillna("Unknown").str.strip().str.title()

    # Reset index
    df = df.reset_index(drop=True)

    print(f"  Rows before cleaning : {initial}")
    print(f"  Rows after  cleaning : {len(df)}")
    print(f"  Rows removed         : {initial - len(df)}\n")

    return df


# ==============================================================================
# 3. DESCRIPTIVE STATISTICS
# ==============================================================================

def describe_data(df):
    print("=" * 60)
    print("STEP 3 — Descriptive Statistics")
    print("=" * 60)

    stats = df[["latest_nav", "return_1y", "return_3y", "fund_age_years"]].describe()
    print(stats.to_string())

    print("\n  Fund distribution by Scheme Type:")
    print(df["scheme_type"].value_counts().to_string())

    print("\n  Fund distribution by Category (Top 10):")
    print(df["scheme_category"].value_counts().head(10).to_string())
    print()

    return stats


# ==============================================================================
# 4. NORMALIZATION
# ==============================================================================

def normalize_data(df):
    print("=" * 60)
    print("STEP 4 — Normalization (MinMaxScaler)")
    print("=" * 60)

    scaler = MinMaxScaler()
    features = ["return_1y", "return_3y", "fund_age_years", "latest_nav"]

    df_norm = df.copy()
    df_norm[features] = scaler.fit_transform(df[features])

    print(f"  Normalized columns: {features}")
    print(f"  All values now in range [0, 1]\n")

    return df_norm, scaler


# ==============================================================================
# 5. SCORING & RANKING
# ==============================================================================

def score_and_rank(df, df_norm):
    """
    Custom scoring formula (weights inspired by the original project):
      - 3-Year Return      : 40%  (most important — long-term performance)
      - 1-Year Return      : 30%  (recent momentum, must be > 0)
      - Expense Ratio      : N/A  (not in mfapi, so fund_age_years proxy used)
      - Fund Age (stable)  : 15%  (moderate age = stability, not too old)
      - NAV (liquidity)    : 15%  (higher NAV = established fund)

    Only funds with 1Y return > 0 are eligible (consistent positive return).
    """
    print("=" * 60)
    print("STEP 5 — Custom Scoring & Ranking")
    print("=" * 60)

    # Filter: only positive 1-year returns
    eligible = df_norm[df["return_1y"] > 0].copy()
    eligible_orig = df[df["return_1y"] > 0].copy()

    print(f"  Eligible funds (1Y return > 0): {len(eligible)}")

    # Score formula
    eligible["score"] = (
        0.40 * eligible["return_3y"] +
        0.30 * eligible["return_1y"] +
        0.15 * eligible["fund_age_years"] +
        0.15 * eligible["latest_nav"]
    )

    eligible_orig["score"] = eligible["score"].values
    ranked = eligible_orig.sort_values("score", ascending=False).reset_index(drop=True)

    print(f"  Scoring weights → 3Y Return: 40%, 1Y Return: 30%, Fund Age: 15%, NAV: 15%")
    print(f"  Top scorer: {ranked.iloc[0]['scheme_name'][:60]}  (score={ranked.iloc[0]['score']:.4f})\n")

    return ranked


# ==============================================================================
# 6. TOP 30 FUNDS
# ==============================================================================

def extract_top30(ranked):
    print("=" * 60)
    print("STEP 6 — Top 30 Mutual Funds")
    print("=" * 60)

    top30 = ranked.head(30).copy()
    top30.index = range(1, 31)

    print(top30[["scheme_name", "fund_house", "scheme_category",
                  "return_1y", "return_3y", "fund_age_years", "score"]].to_string())
    print()

    return top30


# ==============================================================================
# 7. EXPORT TO EXCEL
# ==============================================================================

def export_excel(top30, ranked):
    print("=" * 60)
    print("STEP 7 — Exporting to Excel")
    print("=" * 60)

    with pd.ExcelWriter(TOP30_XLSX, engine="openpyxl") as writer:
        # Sheet 1: Top 30
        top30.to_excel(writer, sheet_name="Top 30 Funds", index=True)

        # Sheet 2: All ranked funds
        ranked.to_excel(writer, sheet_name="All Ranked Funds", index=False)

    print(f"  ✅ Excel saved → {TOP30_XLSX}\n")


# ==============================================================================
# 8. VISUALIZATIONS
# ==============================================================================

def save_chart(fig, filename):
    path = os.path.join(CHARTS_DIR, filename)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved → {path}")


def generate_charts(df, top30, ranked):
    print("=" * 60)
    print("STEP 8 — Generating Charts")
    print("=" * 60)

    # ── Chart 1: Distribution of 1-Year Returns ──────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(df["return_1y"].dropna(), bins=60, color=COLORS[0], edgecolor="white", alpha=0.85)
    ax.axvline(df["return_1y"].mean(), color="red", linestyle="--", linewidth=1.5, label=f"Mean: {df['return_1y'].mean():.1f}%")
    ax.set_title("Distribution of 1-Year Returns (All Funds)", fontsize=14, fontweight="bold")
    ax.set_xlabel("1-Year Return (%)")
    ax.set_ylabel("Number of Funds")
    ax.legend()
    save_chart(fig, "01_return_1y_distribution.png")

    # ── Chart 2: Distribution of 3-Year Returns ──────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(df["return_3y"].dropna(), bins=60, color=COLORS[2], edgecolor="white", alpha=0.85)
    ax.axvline(df["return_3y"].mean(), color="red", linestyle="--", linewidth=1.5, label=f"Mean: {df['return_3y'].mean():.1f}%")
    ax.set_title("Distribution of 3-Year Returns (All Funds)", fontsize=14, fontweight="bold")
    ax.set_xlabel("3-Year Return (%)")
    ax.set_ylabel("Number of Funds")
    ax.legend()
    save_chart(fig, "02_return_3y_distribution.png")

    # ── Chart 3: Fund Count by Scheme Type ───────────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    type_counts = df["scheme_type"].value_counts().head(8)
    bars = ax.barh(type_counts.index, type_counts.values, color=COLORS[:len(type_counts)])
    ax.bar_label(bars, padding=3)
    ax.set_title("Number of Funds by Scheme Type", fontsize=14, fontweight="bold")
    ax.set_xlabel("Count")
    save_chart(fig, "03_funds_by_type.png")

    # ── Chart 4: Average 3Y Return by Category (Top 10) ──────────────────────
    fig, ax = plt.subplots(figsize=(12, 6))
    cat_returns = (
        df.groupby("scheme_category")["return_3y"]
        .mean()
        .dropna()
        .sort_values(ascending=False)
        .head(10)
    )
    bars = ax.bar(range(len(cat_returns)), cat_returns.values, color=COLORS[:len(cat_returns)])
    ax.set_xticks(range(len(cat_returns)))
    ax.set_xticklabels(cat_returns.index, rotation=30, ha="right", fontsize=9)
    ax.bar_label(bars, fmt="%.1f%%", padding=3, fontsize=8)
    ax.set_title("Average 3-Year Return by Fund Category (Top 10)", fontsize=14, fontweight="bold")
    ax.set_ylabel("Avg 3-Year Return (%)")
    save_chart(fig, "04_avg_3y_return_by_category.png")

    # ── Chart 5: Top 10 Fund Houses by Average 1Y Return ─────────────────────
    fig, ax = plt.subplots(figsize=(12, 6))
    amc_returns = (
        df.groupby("fund_house")["return_1y"]
        .agg(["mean", "count"])
        .query("count >= 5")           # min 5 schemes to qualify
        .sort_values("mean", ascending=False)
        .head(10)
    )
    bars = ax.barh(amc_returns.index, amc_returns["mean"], color=COLORS[3])
    ax.bar_label(bars, fmt="%.1f%%", padding=3)
    ax.set_title("Top 10 AMCs by Average 1-Year Return (min 5 schemes)", fontsize=13, fontweight="bold")
    ax.set_xlabel("Avg 1-Year Return (%)")
    save_chart(fig, "05_top_amc_by_return.png")

    # ── Chart 6: Top 30 Funds – Score Comparison (horizontal bar) ────────────
    fig, ax = plt.subplots(figsize=(12, 10))
    labels = [f"{i+1}. {n[:45]}" for i, n in enumerate(top30["scheme_name"])]
    bars = ax.barh(labels[::-1], top30["score"].values[::-1], color=COLORS[1])
    ax.bar_label(bars, fmt="%.3f", padding=3, fontsize=8)
    ax.set_title("Top 30 Mutual Funds — Composite Score", fontsize=14, fontweight="bold")
    ax.set_xlabel("Composite Score")
    ax.tick_params(axis="y", labelsize=8)
    save_chart(fig, "06_top30_scores.png")

    # ── Chart 7: Top 30 – 1Y vs 3Y Returns (scatter) ─────────────────────────
    fig, ax = plt.subplots(figsize=(10, 7))
    sc = ax.scatter(
        top30["return_1y"], top30["return_3y"],
        c=top30["score"], cmap="YlOrRd", s=100, edgecolors="gray", linewidth=0.5
    )
    plt.colorbar(sc, ax=ax, label="Composite Score")
    for _, row in top30.head(10).iterrows():
        ax.annotate(
            row["scheme_name"][:25],
            (row["return_1y"], row["return_3y"]),
            fontsize=6.5, alpha=0.8
        )
    ax.set_title("Top 30 Funds — 1-Year vs 3-Year Returns", fontsize=14, fontweight="bold")
    ax.set_xlabel("1-Year Return (%)")
    ax.set_ylabel("3-Year Return (%)")
    save_chart(fig, "07_top30_return_scatter.png")

    # ── Chart 8: Pie chart – Top 30 by Scheme Category ───────────────────────
    fig, ax = plt.subplots(figsize=(8, 8))
    cat_dist = top30["scheme_category"].value_counts()
    ax.pie(
        cat_dist.values,
        labels=cat_dist.index,
        autopct="%1.1f%%",
        colors=sns.color_palette("pastel", len(cat_dist)),
        startangle=140,
        pctdistance=0.8
    )
    ax.set_title("Top 30 Funds — Category Distribution", fontsize=14, fontweight="bold")
    save_chart(fig, "08_top30_category_pie.png")

    # ── Chart 9: Fund Age Distribution (Top 30) ───────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(top30["fund_age_years"], bins=15, color=COLORS[4], edgecolor="white", alpha=0.85)
    ax.axvline(top30["fund_age_years"].mean(), color="red", linestyle="--",
               label=f"Avg age: {top30['fund_age_years'].mean():.1f} yrs")
    ax.set_title("Fund Age Distribution — Top 30 Funds", fontsize=14, fontweight="bold")
    ax.set_xlabel("Fund Age (Years)")
    ax.set_ylabel("Count")
    ax.legend()
    save_chart(fig, "09_top30_fund_age.png")

    # ── Chart 10: Correlation Heatmap ─────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(7, 5))
    corr = df[["latest_nav", "return_1y", "return_3y", "fund_age_years"]].corr()
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", ax=ax, linewidths=0.5)
    ax.set_title("Correlation Heatmap — Key Metrics", fontsize=14, fontweight="bold")
    save_chart(fig, "10_correlation_heatmap.png")

    print()


# ==============================================================================
# MAIN
# ==============================================================================

def main():
    print("\n" + "=" * 60)
    print("  MUTUAL FUND ANALYSIS — Python Pipeline")
    print("  Data Source: mfapi.in (Free Indian MF API)")
    print("=" * 60 + "\n")

    df_raw = load_data()
    df_clean = clean_data(df_raw)
    describe_data(df_clean)
    df_norm, scaler = normalize_data(df_clean)
    ranked = score_and_rank(df_clean, df_norm)
    top30 = extract_top30(ranked)
    export_excel(top30, ranked)
    generate_charts(df_clean, top30, ranked)

    print("=" * 60)
    print("  ALL DONE!")
    print(f"  📁 Top 30 Excel  → {TOP30_XLSX}")
    print(f"  📊 Charts        → {CHARTS_DIR}/")
    print("=" * 60 + "\n")

    return df_clean, top30, ranked


if __name__ == "__main__":
    main()
